workflows:
  react-native-android:
    name: Build React Native Android App
    max_build_duration: 60
    environment:
      vars:
        NODE_VERSION: 16.13.0  # يمكن تغييره بناءً على المشروع
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
